async function loadData(){return (await fetch('games.json?v=6',{cache:'no-store'})).json()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function gameGroup(g){const p=String(g.platform||'').toLowerCase(),n=String(g.name||'').toLowerCase(),c=String(g.category||'').toLowerCase();if(n.includes('minecraft')||n.includes('actions & stuff')||c.includes('minecraft')||c.includes('mods'))return 'minecraft';if(p.includes('pc')||p.includes('laptop'))return 'pc';return 'android'}
if(document.getElementById('games')){
 loadData().then(d=>{const all=d.games||[],s=document.getElementById('search'),grid=document.getElementById('games'),count=document.getElementById('count'),empty=document.getElementById('empty'),chips=[...document.querySelectorAll('[data-filter]')],clear=document.getElementById('clearFilter');let active='all';
 document.getElementById('heroGameCount').textContent=String(all.length).padStart(2,'0');document.getElementById('year').textContent=new Date().getFullYear();
 function render(){const q=s.value.toLowerCase().trim(),f=all.filter(g=>(active==='all'||gameGroup(g)===active)&&`${g.name} ${g.version} ${g.platform} ${g.category} ${g.short}`.toLowerCase().includes(q));count.textContent=`${f.length} ${f.length===1?'juego':'juegos'}`;empty.classList.toggle('hidden',f.length>0);grid.innerHTML=f.map(g=>`<article class="card"><a class="cover" href="game.html?id=${encodeURIComponent(g.id)}" aria-label="Ver ${esc(g.name)}"><img src="${esc(g.image||'')}" alt="Portada de ${esc(g.name)}" loading="lazy" onerror="this.style.display='none'"><small>${esc(g.platform)}</small><span class="cover-open">↗</span></a><div class="card-body"><p class="eyebrow">${esc(g.category||'JUEGO')}</p><h3>${esc(g.name)}</h3><div class="version">VERSIÓN ${esc(g.version)}</div><p>${esc(g.short||g.description||'Consulta los detalles de este juego.')}</p><div class="card-foot"><span class="platform-dot">● ${esc(gameGroup(g)==='pc'?'PC / LAPTOP':gameGroup(g)==='minecraft'?'MINECRAFT':'ANDROID')}</span><a class="text-link" href="game.html?id=${encodeURIComponent(g.id)}">Ver detalles <b>→</b></a></div></div></article>`).join('');clear.classList.toggle('hidden',active==='all'&&!q);chips.forEach(c=>c.classList.toggle('active',c.dataset.filter===active))}
 function setFilter(f){active=f;render();if(document.getElementById('juegos'))document.getElementById('juegos').scrollIntoView({behavior:'smooth',block:'start'})}
 chips.forEach(c=>c.addEventListener('click',()=>{if(c.tagName==='BUTTON')setFilter(c.dataset.filter)}));s.addEventListener('input',render);clear.addEventListener('click',()=>{s.value='';setFilter('all')});document.querySelectorAll('[data-jump-filter]').forEach(a=>a.addEventListener('click',()=>{active=a.dataset.jumpFilter;render()}));
 document.querySelectorAll('.category-card[data-filter]').forEach(c=>c.addEventListener('click',()=>setFilter(c.dataset.filter)));
 const toggle=document.getElementById('menuToggle'),nav=document.getElementById('mainNav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('nav-open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'✕':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('nav-open');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰'}));render();
 }).catch(err=>{console.error(err);const grid=document.getElementById('games');if(grid)grid.innerHTML='<div class="empty"><h2>No se pudieron cargar los juegos</h2><p>Comprueba que games.json esté en la misma carpeta y vuelve a cargar la página.</p></div>'});
}
